### ISSUE TITLE
リポジトリ名の変更

### ISSUE THREAD

**Issue by betat** [cocopon/Swift-IntroducingOptional.playground#1]
リポジトリ名が `Swift-IntroducingOptional.playground` であると、
`git clone` したものに対して Mac が Xcode で開こうとしエラーが発生します。

実際には、`Swift-IntroducingOptional.playground` 内にある
`IntroducingOptional.playground` が対象の Playground であり、
それに気づかず悩む人がいるかもしれません。

**Comment by cocopon** [comment]
ご指摘ありがとうございます！

途中で構成を変更したのですが、リポジトリ名はそのまま残ってしまっていました…。修正しました。
